import React, { useState, useEffect, useLayoutEffect } from 'react';
import {UserOutlined } from '@ant-design/icons';
import { Layout, Menu, theme, Pagination } from 'antd';
const { Content, Footer, Sider } = Layout;
import Head from 'next/head';
import 'antd/dist/reset.css';
import axios from "axios";
import CustomHeader from '../components/CustomHeader';
import Cards from '../components/Cards';
import routes from '../routes';

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

// const Movies = ({genres, movies}) => {
const Movies = ({genres}) => {
  const [page, setPage] = useState(1);
  const [selectedGenres, setSelectedGenres] = useState([]);
  const [moviesData, setMoviesData] = useState([]);
  const [totalMoviesResult, setTotalMoviesResult] = useState(0)

  const filters = [UserOutlined].map((icon, index) => {
    return {
      key: `genres`,
      icon: React.createElement(icon),
      label: `Genres`,
      children: genres.map((el) => ({ key: el.id, label: el.name })),
    };
  });

  const getMoviesData = async(pageNumber) => {
    console.log('in get', selectedGenres.toString())
    const moviesUrl = routes.getDiscoverByGenresPath('movie', selectedGenres.toString(), pageNumber);
    const res = await axios.get(moviesUrl);
    // console.log(res)
    setMoviesData(() => res.data.results.map((el) => ({ ...el, 'media_type': 'movie' })));
    console.log(res.data.total_results)
    setTotalMoviesResult(res.data.total_results);
  }
  
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  
  const onSelect = async(e) => {
    const newSelectedGenres = [...selectedGenres, e.key]
    setSelectedGenres(newSelectedGenres);
  }

  const onDeselect = async(e) => {
    const newSelectedGenres = selectedGenres.filter((el) => el !== e.key)
    setSelectedGenres(newSelectedGenres);
  }

  const onPaginationChange = async(current) => {
    setPage(current);
  };

  useEffect(() => {
    getMoviesData(page)
    console.log('in movies', moviesData)
  }, [selectedGenres, page]);

  return (
    <Layout>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomHeader />
      <Content
        className='main-content'
      >
        <Layout
          className='main-layout'
        >
          <Sider
            style={{
              background: colorBgContainer,
            }}
            width={200}
          >
            <Menu
              mode="inline"
              defaultSelectedKeys={['1']}
              defaultOpenKeys={['genres']}
              style={{
                height: '100%',
              }}
              items={filters}
              multiple='true'
              onSelect={onSelect}
              onDeselect={onDeselect}
            />
          </Sider>
          <Content>
            {/* {moviesData ? (<Cards data={moviesData} onPaginationChange={onPaginationChange} page={page} /> ) : null} */}
            <Cards data={moviesData} />
            <Pagination
              current={page}
              onChange={onPaginationChange}
              total={totalMoviesResult}
              pageSize = {20}
              className='pagination' />                       
          </Content>
        </Layout>
      </Content>
      <Footer>
        Cinema ©2022 Created by pavl1k
      </Footer>
    </Layout>
  );
};
export default Movies;

export async function getStaticProps() {
  const genresUrl = routes.getGenresPath('movie');
  const res = await axios.get(genresUrl);
  const genresData = res.data.genres;

  // const moviesUrl = routes.getDiscoverByGenresPath('movie', '', 1);
  // const movies = (await axios.get(moviesUrl)).data.results;
  return {
    props: {
      genres: genresData,
      // movies
    },
  };
}

