import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { Layout, Menu, theme, Pagination, Spin, Alert } from 'antd';
import { UserOutlined } from '@ant-design/icons';
import 'antd/dist/reset.css';
import CustomHeader from '../components/CustomHeader';
import Cards from '../components/Cards';
import routes from '../routes';
import axios from "axios";

const { Content, Footer, Sider } = Layout;
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const Movies = ({ genres }) => {
  const [page, setPage] = useState(null);
  const [selectedGenres, setSelectedGenres] = useState([]);
  const [moviesData, setMoviesData] = useState([]);
  const [totalMoviesResult, setTotalMoviesResult] = useState(0);
  const [showLoad, setShowLoad] = useState(false);
  const [showError, setShowError] = useState(false);

  const filters = [UserOutlined].map((icon) => {
    return {
      key: `genres`,
      icon: React.createElement(icon),
      label: `Genres`,
      children: genres.map((el) => ({ key: el.id, label: el.name })),
    };
  });
  
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  
  const onSelect = async(e) => {
    const newSelectedGenres = [...selectedGenres, e.key]
    setSelectedGenres(newSelectedGenres);
    setPage(1);
    localStorage.setItem('movies_page', 1);
  }

  const onDeselect = async(e) => {
    const newSelectedGenres = selectedGenres.filter((el) => el !== e.key)
    setSelectedGenres(newSelectedGenres);
    localStorage.setItem('movies_page', 1);
    setPage(1);
  }

  const onPaginationChange = async(current) => {
    localStorage.setItem('movies_page', current);
    setPage(current);    
  };

  useEffect(() => {
    const getMoviesData = async(pageNumber) => {
      console.log('getMoviesData')
      const moviesUrl = routes.getDiscoverByGenresPath('movie', selectedGenres.toString(), pageNumber);
      setShowLoad(true);
      try {
        const res = await axios.get(moviesUrl);
        const { results, total_results: totalResults } = res.data;
        setMoviesData(() => results.map((el) => ({ ...el, media_type: 'movie' })));
        setTotalMoviesResult(() => totalResults);
        setShowLoad(false);
        setShowError(false);
      } catch (e) {
        console.log('error', e);
        setShowError(true);
        setShowLoad(false);
      }
    };
    
    const movies_page = localStorage.getItem('movies_page') ?? 1;
    setPage(+movies_page);
    
    if (page) {
      getMoviesData(page);
    }
    
    // console.log('in movies data');
  }, [selectedGenres, page]);

  return (
    <Layout>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomHeader />
      <Content
        className='main-content'
      >
        <Layout
          className='main-layout'
        >
          <Sider
            style={{
              background: colorBgContainer,
            }}
            width={200}
          >
            <Menu
              mode="inline"
              defaultSelectedKeys={['1']}
              defaultOpenKeys={['genres']}
              items={filters}
              multiple='true'
              onSelect={onSelect}
              onDeselect={onDeselect}
            />
          </Sider>
          <Content>
            {(showLoad && !showError) ? (
            <Spin tip="Loading" size="large">
              <div className="content" />
            </Spin>): null}
            {(!showLoad && showError) ? (
              <Alert
                message="Что пошло не так"
                description="Попробуйте перезагрузить страницу чуть позже"
                type="error"
              />
            ): null}
            {(!showLoad && !showError) ? (
              <>
                <Cards data={moviesData} />
                <Pagination
                    current={page}
                    onChange={onPaginationChange}
                    total={totalMoviesResult}
                    pageSize = {20}
                    className='pagination' />
              </>): null}
          </Content>
        </Layout>
      </Content>
      <Footer>
        Cinema ©2022 Created by pavl1k
      </Footer>
    </Layout>
  );
};
export default Movies;

export async function getStaticProps() {
  const genresUrl = routes.getGenresPath('movie');
  try {
    const res = await axios.get(genresUrl);
    const genresData = res.data.genres;

    return {
      props: {
        genres: genresData,
      },
    };
  } catch (e) {
    console.log(e);
    return {
      props: {
        genres: [],
      },
    };
  }  
}

